### PR TITLE
feat: fix replicasets so that pods are mutated and created

### LINKED ISSUE #43: protect-webhook failing with replicaset
### Describe the bug

I'm testing out protect-webhook by spinning up a microservice cluster, implementing the webhook, and then deleting the pod to then run as an Edera Protect workload.

The pod doesn't come back, when describing the replica set I see:

```sh
Events:
  Type     Reason            Age                    From                   Message
  ----     ------            ----                   ----                   -------
  Warning  FailedCreate      8m38s (x7 over 8m39s)  replicaset-controller  Error creating: pods "adservice-997b6fc95-" is forbidden: error looking up service account default/adservice: serviceaccount "adservice" not found
  Normal   SuccessfulCreate  8m38s                  replicaset-controller  Created pod: adservice-997b6fc95-smkk9
  Warning  FailedCreate      1s (x14 over 33s)      replicaset-controller  Error creating: Internal error occurred: failed calling webhook "mutate-protect-webhook.edera.dev": failed to call webhook: the server rejected our request for an unknown reason
```

When checking the logs of the mutate webhook I see:

```sh
kubectl logs -n edera-system mutate-protect-webhook-769f9ff769-74nbk
[2025-02-11T09:00:24Z INFO  protect_webhook::server] configured certs directory to: /certs
[2025-02-11T09:00:24Z INFO  protect_webhook::server] listening on 8443
[2025-02-11T09:00:24Z INFO  warp::server] TlsServer::run; addr=0.0.0.0:8443
[2025-02-11T09:00:24Z INFO  warp::server] listening on https://0.0.0.0:8443
```

This might be due to the runtime changing, and breaking the replica set.

### Steps To Reproduce

1. Create Edera EKS cluster
2. Git clone github.com/googlecloudplatform/microservices-demo/
3. Apply the following yaml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  labels:
    app: adservice
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      serviceAccountName: adservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice:v0.10.2
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 9555
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 9555
```

5. Setup https://github.com/edera-dev/protect-webhook
6. `kubectl delete pod adservice-997b6fc95-smkk9`
7. `kubectl get pods -n default`
8. `kubectl describe rs adservice-997b6fc95`
9. `kubectl logs -n edera-system mutate-protect-webhook-769f9ff769-74nbk`
10. Added this to the values.yaml:```yaml
logLevel: debug
```

10. Checked the logs on the protect-webhook pod and received the following:

```sh
kubectl logs -n edera-system mutate-protect-webhook-5f9c8b8c84-9ngtp
[2025-02-11T14:59:16Z INFO  protect_webhook::server] configured certs directory to: /certs
[2025-02-11T14:59:16Z INFO  protect_webhook::server] listening on 8443
[2025-02-11T14:59:16Z INFO  warp::server] TlsServer::run; addr=0.0.0.0:8443
[2025-02-11T14:59:16Z INFO  warp::server] listening on https://0.0.0.0:8443
[2025-02-11T14:59:16Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T14:59:24Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T14:59:24Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T14:59:34Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T14:59:34Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T14:59:44Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T14:59:44Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T14:59:54Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T14:59:54Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T15:00:04Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T15:00:04Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T15:00:14Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T15:00:14Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T15:00:24Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T15:00:24Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T15:00:34Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T15:00:34Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T15:00:44Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T15:00:44Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T15:00:54Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T15:00:54Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T15:01:04Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T15:01:04Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T15:01:14Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T15:01:14Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T15:01:23Z DEBUG rustls::server::hs] decided upon suite TLS13_AES_128_GCM_SHA256
[2025-02-11T15:01:23Z DEBUG rustls::server::tls13::client_hello] Client unwilling to resume, DHE_KE not offered
[2025-02-11T15:01:23Z DEBUG rustls::server::hs] Chosen ALPN protocol [104, 116, 116, 112, 47, 49, 46, 49]
[2025-02-11T15:01:23Z DEBUG hyper::proto::h1::io] parsed 6 headers
[2025-02-11T15:01:23Z DEBUG hyper::proto::h1::conn] incoming body is content-length (4759 bytes)
[2025-02-11T15:01:23Z DEBUG hyper::proto::h1::conn] incoming body completed
[2025-02-11T15:01:23Z DEBUG warp::filters::body] request json body error: missing field `name` at line 1 column 4757
[2025-02-11T15:01:23Z DEBUG warp::filter::service] rejected: Rejection([MethodNotAllowed, MethodNotAllowed, BodyDeserializeError { cause: Error("missing field `name`", line: 1, column: 4757) }])
[2025-02-11T15:01:23Z DEBUG hyper::proto::h1::io] flushed 200 bytes
[2025-02-11T15:01:24Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T15:01:24Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T15:01:24Z DEBUG hyper::proto::h1::io] parsed 6 headers
[2025-02-11T15:01:24Z DEBUG hyper::proto::h1::conn] incoming body is content-length (4759 bytes)
[2025-02-11T15:01:24Z DEBUG hyper::proto::h1::conn] incoming body completed
[2025-02-11T15:01:24Z DEBUG warp::filters::body] request json body error: missing field `name` at line 1 column 4757
[2025-02-11T15:01:24Z DEBUG warp::filter::service] rejected: Rejection([MethodNotAllowed, MethodNotAllowed, BodyDeserializeError { cause: Error("missing field `name`", line: 1, column: 4757) }])
[2025-02-11T15:01:24Z DEBUG hyper::proto::h1::io] flushed 200 bytes
[2025-02-11T15:01:27Z DEBUG hyper::proto::h1::io] parsed 6 headers
[2025-02-11T15:01:27Z DEBUG hyper::proto::h1::conn] incoming body is content-length (4759 bytes)
[2025-02-11T15:01:27Z DEBUG hyper::proto::h1::conn] incoming body completed
[2025-02-11T15:01:27Z DEBUG warp::filters::body] request json body error: missing field `name` at line 1 column 4757
[2025-02-11T15:01:27Z DEBUG warp::filter::service] rejected: Rejection([MethodNotAllowed, MethodNotAllowed, BodyDeserializeError { cause: Error("missing field `name`", line: 1, column: 4757) }])
[2025-02-11T15:01:27Z DEBUG hyper::proto::h1::io] flushed 200 bytes
[2025-02-11T15:01:32Z DEBUG hyper::proto::h1::io] parsed 6 headers
[2025-02-11T15:01:32Z DEBUG hyper::proto::h1::conn] incoming body is content-length (4759 bytes)
[2025-02-11T15:01:32Z DEBUG hyper::proto::h1::conn] incoming body completed
[2025-02-11T15:01:32Z DEBUG warp::filters::body] request json body error: missing field `name` at line 1 column 4757
[2025-02-11T15:01:32Z DEBUG warp::filter::service] rejected: Rejection([MethodNotAllowed, MethodNotAllowed, BodyDeserializeError { cause: Error("missing field `name`", line: 1, column: 4757) }])
[2025-02-11T15:01:32Z DEBUG hyper::proto::h1::io] flushed 200 bytes
[2025-02-11T15:01:34Z DEBUG hyper::proto::h1::conn] read eof
[2025-02-11T15:01:34Z DEBUG hyper::proto::h1::conn] read eof
```

### Expected Behavior

Pod to be running within Edera Protect runtime.

### PR DESCRIPTION
**Pull request by denhamparry**
- Closes #43.
- Show received  `yaml` when `logLevel` is `debug`.
- Manage pods created via ReplicaSets.
- Prayers made to the demo and PR gods.

### CODE REVIEW

File: src/server/mutate.rs [hunk 1]
```diff
@@ -56,12 +102,30 @@ async fn mutate_internal(review: AdmissionReview) -> Result<impl warp::Reply, wa
...
+        metadata
+            .generate_name
+            .unwrap_or_else(|| "unknown".to_string())
+    });
+    let namespace = metadata.namespace;
+
+    // Determine patch path based on object kind. Default to pod.
+    let patch_path = if let Some(kind_info) = &request.kind {
+        match kind_info.kind.as_str() {
+            "Deployment" | "ReplicaSet" | "StatefulSet" => "/spec/template/spec/runtimeClassName",
```
Comment (found-it) [inline src/server/mutate.rs:117]: Should we add DaemonSet here too?

**Review by found-it — COMMENTED** [review]
Overall looks fantastic @denhamparry!

I'd love to see a test for a higher level object (replicaset, etc) to make sure we don't break anything there. Otherwise just one comment.

File: src/server/mutate.rs (hunk 1 above)
Comment (denhamparry) [reply src/server/mutate.rs:117]: Checked https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/ and I'd agree!

**Comment by denhamparry** [comment]
Now with added tests 🧪

File: src/server/mutate.rs [hunk 2]
```diff
@@ -56,12 +102,50 @@ async fn mutate_internal(review: AdmissionReview) -> Result<impl warp::Reply, wa
...
+    // Get name and namespace from the object's metadata.
+    let metadata = request.object.metadata;
+    let name = metadata.name.unwrap_or_else(|| {
+        metadata
+            .generate_name
+            .unwrap_or_else(|| "unknown".to_string())
+    });
+    let namespace = metadata.namespace;
+
+    // Prevent mutating resources in the kube-system namespace
```
Comment (found-it) [inline src/server/mutate.rs:114]: @denhamparry I'd prefer to lift this out to a configuration rather than being implicit inside the server itself. Eventually we may want to `kube-system` resources and it would be good for end users to see which namespaces are being excluded through the configuration rather than the logs.

I'm fine if we merge this and file an issue to add more configuration options

**Review by found-it — APPROVED** [review]
